import { useEffect, useMemo, useRef, useState, type DragEvent, type FormEvent } from "react";
import { useNavigate } from "react-router-dom";
import { supabase } from "../lib/supabase";

const categories = ["Dresses", "Sets", "Skirt", "Tops"];
const MAX_IMAGE_SIZE = 6 * 1024 * 1024;
type StatusFilter = "all" | "available" | "taken" | "published" | "hidden";
type AdminProduct = { id: string; slug: string; name: string; price: string; description: string; category: string; sizes: string; image_url: string | null; image_path: string | null; in_stock: boolean; published: boolean; created_at: string; };

export default function AdminProductsPage() {
  const navigate = useNavigate();
  const fileRef = useRef<HTMLInputElement>(null);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [name, setName] = useState(""); const [price, setPrice] = useState(""); const [description, setDescription] = useState(""); const [category, setCategory] = useState("Dresses"); const [sizes, setSizes] = useState("XS – XL"); const [image, setImage] = useState<File | null>(null); const [preview, setPreview] = useState(""); const [inStock, setInStock] = useState(true); const [published, setPublished] = useState(true);
  const [products, setProducts] = useState<AdminProduct[]>([]); const [productsLoading, setProductsLoading] = useState(true); const [saving, setSaving] = useState(false); const [uploadProgress, setUploadProgress] = useState(0); const [message, setMessage] = useState(""); const [messageType, setMessageType] = useState<"success" | "error" | "info">("info"); const [query, setQuery] = useState(""); const [statusFilter, setStatusFilter] = useState<StatusFilter>("all");

  const notify = (text: string, type: "success" | "error" | "info" = "info") => { setMessage(text); setMessageType(type); };
  const createSlug = (value: string) => value.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
  async function loadProducts() { setProductsLoading(true); const { data, error } = await supabase.from("products").select("*").order("created_at", { ascending: false }); if (error) { notify(`Could not load products: ${error.message}`, "error"); setProductsLoading(false); return; } setProducts(((data ?? []) as AdminProduct[]).map((p) => ({ ...p, category: p.category === "Abayas" ? "Skirt" : p.category }))); setProductsLoading(false); }
  useEffect(() => { loadProducts(); }, []);
  useEffect(() => () => { if (preview.startsWith("blob:")) URL.revokeObjectURL(preview); }, [preview]);

  function selectImage(file: File | null) { if (!file) return; if (!file.type.startsWith("image/")) { notify("Please choose a JPEG, PNG, or WebP image.", "error"); return; } if (file.size > MAX_IMAGE_SIZE) { notify("Please choose an image smaller than 6 MB.", "error"); return; } setImage(file); setPreview(URL.createObjectURL(file)); notify("Image ready to upload.", "info"); }
  function onDrop(event: DragEvent<HTMLDivElement>) { event.preventDefault(); selectImage(event.dataTransfer.files?.[0] ?? null); }
  function startEdit(product: AdminProduct) { setEditingId(product.id); setName(product.name); setPrice(product.price); setDescription(product.description); setCategory(product.category); setSizes(product.sizes); setInStock(product.in_stock); setPublished(product.published); setImage(null); setPreview(product.image_url ?? ""); notify(`Editing ${product.name}.`, "info"); window.scrollTo({ top: 0, behavior: "smooth" }); }
  function resetForm() { setEditingId(null); setName(""); setPrice(""); setDescription(""); setCategory("Dresses"); setSizes("XS – XL"); setImage(null); setPreview(""); setInStock(true); setPublished(true); setUploadProgress(0); if (fileRef.current) fileRef.current.value = ""; }

  async function handleSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const slug = createSlug(name); if (!slug) return notify("Please enter a valid outfit name.", "error"); if (!editingId && !image) return notify("Please select an outfit image.", "error"); setSaving(true); setUploadProgress(12); setMessage("");
    const existing = editingId ? products.find((p) => p.id === editingId) : null; let imageUrl = existing?.image_url ?? null; let imagePath = existing?.image_path ?? null;
    if (image) { const extension = image.name.split(".").pop()?.toLowerCase() || "jpg"; imagePath = `${slug}-${crypto.randomUUID()}.${extension}`; const upload = await supabase.storage.from("product-images").upload(imagePath, image, { contentType: image.type, cacheControl: "3600", upsert: false }); if (upload.error) { notify(`Image upload failed: ${upload.error.message}`, "error"); setSaving(false); setUploadProgress(0); return; } imageUrl = supabase.storage.from("product-images").getPublicUrl(imagePath).data.publicUrl; setUploadProgress(70); }
    const values = { slug, name: name.trim(), price: price.trim(), description: description.trim(), category, sizes: sizes.trim(), image_url: imageUrl, image_path: imagePath, in_stock: inStock, published };
    const result = editingId ? await supabase.from("products").update(values).eq("id", editingId) : await supabase.from("products").insert(values);
    if (result.error) { if (imagePath && image && imagePath !== existing?.image_path) await supabase.storage.from("product-images").remove([imagePath]); notify(`Product could not be saved: ${result.error.message}`, "error"); setSaving(false); setUploadProgress(0); return; }
    if (image && existing?.image_path && existing.image_path !== imagePath) await supabase.storage.from("product-images").remove([existing.image_path]); setUploadProgress(100); notify(editingId ? "Outfit updated successfully." : "Outfit published successfully.", "success"); resetForm(); setSaving(false); await loadProducts();
  }
  async function toggleStock(product: AdminProduct) { const next = !product.in_stock; const { error } = await supabase.from("products").update({ in_stock: next }).eq("id", product.id); if (error) return notify(`Could not update availability: ${error.message}`, "error"); setProducts((list) => list.map((p) => p.id === product.id ? { ...p, in_stock: next } : p)); notify(`${product.name} is marked as ${next ? "available" : "taken"}.`, "success"); }
  async function togglePublished(product: AdminProduct) { const next = !product.published; const { error } = await supabase.from("products").update({ published: next }).eq("id", product.id); if (error) return notify(`Could not update visibility: ${error.message}`, "error"); setProducts((list) => list.map((p) => p.id === product.id ? { ...p, published: next } : p)); notify(`${product.name} is now ${next ? "visible" : "hidden"} in the shop.`, "success"); }
  async function deleteProduct(product: AdminProduct) { if (!window.confirm(`Delete “${product.name}” permanently? This cannot be undone.`)) return; setMessage(""); if (product.image_path) { const { error } = await supabase.storage.from("product-images").remove([product.image_path]); if (error) return notify(`Could not delete product image: ${error.message}`, "error"); } const { error } = await supabase.from("products").delete().eq("id", product.id); if (error) return notify(`Could not delete product: ${error.message}`, "error"); setProducts((list) => list.filter((p) => p.id !== product.id)); notify(`${product.name} was deleted.`, "success"); }
  async function signOut() { await supabase.auth.signOut(); navigate("/admin/login"); }

  const filteredProducts = useMemo(() => products.filter((p) => { const matchesQuery = `${p.name} ${p.category} ${p.price}`.toLowerCase().includes(query.toLowerCase()); const matchesStatus = statusFilter === "all" || (statusFilter === "available" && p.in_stock) || (statusFilter === "taken" && !p.in_stock) || (statusFilter === "published" && p.published) || (statusFilter === "hidden" && !p.published); return matchesQuery && matchesStatus; }), [products, query, statusFilter]);
  const stats = { total: products.length, available: products.filter((p) => p.in_stock).length, taken: products.filter((p) => !p.in_stock).length, hidden: products.filter((p) => !p.published).length };

  return <main className="admin-page"><div className="wrap admin-card"><div className="admin-header"><div><p className="eyebrow">Collection manager</p><h1>{editingId ? "Edit an outfit" : "Add an outfit"}</h1></div><button className="btn btn-outline admin-signout" type="button" onClick={signOut}>Sign out</button></div>
    <div className="admin-stats" aria-label="Collection statistics"><div><strong>{stats.total}</strong><span>Total products</span></div><div><strong>{stats.available}</strong><span>Available</span></div><div><strong>{stats.taken}</strong><span>Taken</span></div><div><strong>{stats.hidden}</strong><span>Hidden</span></div></div>
    <form className="admin-form" onSubmit={handleSubmit}>
      <label>Outfit name<input value={name} onChange={(e) => setName(e.target.value)} placeholder="The Amara Dress" required /></label><label>Price<input value={price} onChange={(e) => setPrice(e.target.value)} placeholder="KSh 4,500" required /></label><label>Category<select value={category} onChange={(e) => setCategory(e.target.value)}>{categories.map((item) => <option key={item}>{item}</option>)}</select></label><label>Available sizes<input value={sizes} onChange={(e) => setSizes(e.target.value)} placeholder="XS – XL, made to order" required /></label><label>Description<textarea value={description} onChange={(e) => setDescription(e.target.value)} placeholder="Describe the outfit, fabric, fit, and details." rows={5} required /></label>
      <div className="admin-upload-zone" onDragOver={(e) => e.preventDefault()} onDrop={onDrop}><label>Outfit photo<input ref={fileRef} type="file" accept="image/jpeg,image/png,image/webp" onChange={(e) => selectImage(e.target.files?.[0] ?? null)} required={!editingId} /></label><p>Drag and drop an image here, or choose a file. JPG, PNG or WebP up to 6 MB.</p>{preview && <img className="admin-preview" src={preview} alt="Selected outfit preview" onError={() => notify("The selected image could not be previewed.", "error")} />}</div>
      <label className="checkbox-label"><input type="checkbox" checked={inStock} onChange={(e) => setInStock(e.target.checked)} /> Available to order</label><label className="checkbox-label"><input type="checkbox" checked={published} onChange={(e) => setPublished(e.target.checked)} /> Visible in shop</label>
      {saving && <div className="admin-progress" aria-live="polite"><div style={{ width: `${uploadProgress}%` }} /><span>{uploadProgress < 70 ? "Preparing image…" : uploadProgress < 100 ? "Saving outfit…" : "Complete"} {uploadProgress}%</span></div>}
      <div className="admin-form__actions"><button className="btn" type="submit" disabled={saving}>{saving ? "Saving…" : editingId ? "Save changes" : "Publish outfit"}</button>{editingId && <button className="btn btn-outline" type="button" onClick={resetForm}>Cancel edit</button>}</div>
      {message && <p className={`admin-message admin-message--${messageType}`} role={messageType === "error" ? "alert" : "status"}>{message}</p>}
    </form>
    <section className="admin-products"><div className="admin-products__heading"><div><p className="eyebrow">Current collection</p><h2>Manage outfits</h2></div><button className="btn btn-outline" type="button" onClick={loadProducts} disabled={productsLoading}>{productsLoading ? "Loading…" : "Refresh"}</button></div>
      <div className="admin-filters"><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search outfits…" aria-label="Search outfits" /><select value={statusFilter} onChange={(e) => setStatusFilter(e.target.value as StatusFilter)} aria-label="Filter products by status"><option value="all">All statuses</option><option value="available">Available</option><option value="taken">Taken</option><option value="published">Visible in shop</option><option value="hidden">Hidden</option></select></div>
      {productsLoading ? <div className="collection__status"><p className="eyebrow">Please wait</p><h2>Loading collection…</h2></div> : products.length === 0 ? <div className="collection__status"><p className="eyebrow">Your collection</p><h2>No outfits yet.</h2><p>Add your first outfit using the form above.</p></div> : filteredProducts.length === 0 ? <div className="collection__status"><p className="eyebrow">No matches</p><h2>No outfits match that filter.</h2></div> : <div className="admin-products__list">{filteredProducts.map((product) => <article className="admin-product" key={product.id}>{product.image_url ? <img src={product.image_url} alt={`${product.name} outfit`} className="admin-product__image" onError={(e) => { e.currentTarget.style.display = "none"; }} /> : <div className="admin-product__image admin-product__image--empty">No image</div>}<div className="admin-product__details"><p className="eyebrow">{product.category}</p><h3>{product.name}</h3><p>{product.price}</p><div className="admin-product__statuses"><span className={`status ${product.in_stock ? "status--available" : "status--taken"}`}>{product.in_stock ? "Available" : "Taken"}</span><span className={`status ${product.published ? "status--published" : "status--hidden"}`}>{product.published ? "Visible" : "Hidden"}</span></div></div><div className="admin-product__actions"><button className="btn btn-outline" type="button" onClick={() => startEdit(product)}>Edit</button><button className="btn btn-outline" type="button" onClick={() => toggleStock(product)}>{product.in_stock ? "Mark taken" : "Mark available"}</button><button className="btn btn-outline" type="button" onClick={() => togglePublished(product)}>{product.published ? "Hide" : "Show"}</button><button className="btn btn-danger" type="button" onClick={() => deleteProduct(product)}>Delete</button></div></article>)}</div>}
    </section>
  </div></main>;
}
